import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// @'et i pathen betyder bare at den går til next.js appen's root
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// NextThemesProvider er en "provider", hvilket er noget man ligger rundt om sin app for at give den adgang til data.
// NextThemesProvider - giver appen adgang til light / dark mode data
// Providers er generelt/typisk clientside ("use client")
// Eftersom skiftet mellem light og dark mode kræver en bruger til at skifte <-- brugerinteraktion == vi skal bruge en client

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider attribute="class" defaultTheme="dark">
					<main className="flex min-h-screen flex-col items-center p-24">
						<div className="z-10 w-full max-w-5xl items-center justify-between text-sm lg:flex">
							<h2 className="text-2xl text-bold">
								PokemonSearcher
							</h2>
						</div>
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
